name: CI

on:
  pull_request_target:
    types: [ opened, reopened, ready_for_review, synchronize ]
  workflow_dispatch:

env:
  LOGFILE: logs-${{ github.event.pull_request.repo.owner.login }}-${{ github.event.pull_request.repo.name }}-${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.sha }}

jobs:
  Starting:
    runs-on: ubuntu-latest
    steps:
      - name: Display CI Info
        run: |
          echo CI starting for the following:
          echo org: ${{ github.event.pull_request.repo.owner.login }}
          echo repo: ${{ github.event.pull_request.repo.name }}
          echo pr: ${{ github.event.pull_request.number }}:
          echo commit: ${{ github.event.pull_request.head.sha }}
          echo action: ${{ github.event.action }}

      # Run assignment action
      - name: Assign reviewers and assignees
        uses: dm-vdo/vdo-auto-assign@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove all known labels
        uses: buildsville/add-remove-label@v2.0.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          labels: untested, private testing running, private testing done, private testing failed
          type: remove

      - name: Add untested label
        if: ${{ steps.is_organization_member.outputs.result == 'true' }}
        uses: buildsville/add-remove-label@v2.0.0
        with:
          token: ${{secrets.VDODEVEL}}
          label: untested
          type: add

  Private-Testing:
    if: github.event.pull_request.draft == false
    runs-on: [self-hosted, trusted]
    needs: [Starting]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Start Private testing
        run: echo Private Testing Start

      - name: Add testing running label
        uses: buildsville/add-remove-label@v2.0.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: private testing running
          type: add

      - name: Remove untested label
        uses: buildsville/add-remove-label@v2.0.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: untested
          type: remove

      - name: Run-trusted-Tests
        run: |
          make -j4 M=drivers/md/dm-vdo

      - name: Copy log file to /permatbit/user/bunsen/artifacts
        if: failure()
        run: |
          cp -a logs /permabit/user/bunsen/artifacts/${{ env.LOGFILE }}

      - name: Remove private testing running label
        if: always()
        uses: buildsville/add-remove-label@v2.0.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: private testing running
          type: remove

      - name: Add private testing failed
        if: failure()
        uses: buildsville/add-remove-label@v2.0.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: private testing failed
          type: add

      - name: Add private testing success
        if: success()
        uses: buildsville/add-remove-label@v2.0.0
        with:
          token: ${{secrets.VDODEVEL}}
          label: private testing done
          type: add
